### ISSUE TITLE
Skaffe varebil / tilhenger til opp og nedrigging

### ISSUE THREAD

**Issue by vnys** [florvagfau/17-mai-2023#56]
Trenger vi dette? Sjekke med @Orjstu.

**Comment by Orjstu** [comment]
Skaffer henger, trenger til frakt av telt, fryseboks. Etc.



Sendt fra min Galaxy



-------- Opprinnelig melding --------
Fra: Victor Nystad ***@***.***>
Dato: 17.04.2023 21:32 (GMT+01:00)
Til: florvagfau/17-mai-2023 ***@***.***>
Ko: Orjstu ***@***.***>, Mention ***@***.***>
Emne: [florvagfau/17-mai-2023] Skaffe varebil / tilhenger til opp og nedrigging (Issue #56)


Trenger vi dette? Sjekke med @Orjstu<https://github.com/Orjstu>.

**Comment by vnys** [comment]
Supert, da lukker jeg denne.
